#
# gem install jekyll bundler
# bundle install 
# 
# bundle exec jekyll serve
# 
title: Johny W. Alves
description: > # this means to ignore newlines until "baseurl:"
  Meu nome é Johny William de Oliveira Alves amo aprender, criei esse espaço para organizar meus estudos, compartilhar e receber feedback.
permalink: ':title'
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog
url: "https://lab.johnywalves.com.br" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Johny W. Alves # add your name
author-img: johnywalves.jpg # add your photo
about-author: Desenvolvedor full-stack e cientista de dados. Sempre aprendendo e amando o processo. # add description
social-github: johnywalves
social-linkedin: johnywalves
social-instagram: johnywalves
social-twitter: johnywalves
social-facebook: johnywalves
social-email: contato@johnywalves.com.br

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-125055658-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
